# Generated by Django 3.1.4 on 2021-01-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210101_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50, verbose_name='路径')),
                ('component', models.CharField(max_length=50, verbose_name='组件')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('icon', models.CharField(max_length=50, verbose_name='图表')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name_plural': '菜单表',
                'db_table': 'tb_menu',
            },
        ),
    ]
