# Generated by Django 3.1.4 on 2021-01-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('menu', models.ManyToManyField(related_name='menus', to='user.Menu')),
                ('user', models.ManyToManyField(related_name='roles', to='user.User')),
            ],
            options={
                'verbose_name_plural': '角色表',
                'db_table': 'tb_roles',
            },
        ),
    ]
