# Generated by Django 3.1.4 on 2021-01-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='redirect',
            field=models.CharField(default='/menu', max_length=50, verbose_name='重定向页面'),
        ),
    ]
