# Generated by Django 3.1.4 on 2021-01-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_menu_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='redirect',
            field=models.CharField(max_length=50, verbose_name='重定向页面'),
        ),
    ]
