# Generated by Django 3.1.4 on 2021-01-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210103_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='redirect',
            field=models.CharField(blank=True, max_length=50, verbose_name='重定向页面'),
        ),
    ]
