# Generated by Django 3.1.4 on 2021-01-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210103_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='user',
        ),
        migrations.AddField(
            model_name='menu',
            name='ctm',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='menu',
            name='utm',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='roles',
            name='ctm',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='roles',
            name='utm',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='user.Roles', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='menu',
            field=models.ManyToManyField(related_name='menus', to='user.Menu', verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=50, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ctm',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='更新时间'),
        ),
    ]
