# Generated by Django 3.1.4 on 2021-01-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210103_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ctm',
            field=models.BigIntegerField(blank=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='utm',
            field=models.BigIntegerField(blank=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='ctm',
            field=models.BigIntegerField(blank=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='utm',
            field=models.BigIntegerField(blank=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ctm',
            field=models.BigIntegerField(blank=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm',
            field=models.BigIntegerField(blank=True, verbose_name='更新时间'),
        ),
    ]
