# Generated by Django 3.1.4 on 2021-01-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210103_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='menu',
            field=models.ManyToManyField(related_name='roles', to='user.Menu', verbose_name='菜单'),
        ),
    ]
